### ISSUE TITLE
How to verify fileMatch?

### ISSUE THREAD

**Issue by giacomorebonato** [BlueGlassBlock/better-json5#3]
First of all thank you for this extension, it was very needed!

How can I tell if the fileMatching is working?
I am not getting the autocomplete from the schema and I am looking for the root cause.

```
  "json5.schemas": [
    {
      "fileMatch": [
        "test.json5"
      ],
      "schema": true,
      "url": "../my-schema.json"
    },
 ]
```

**Comment by BlueGlassBlock** [comment]
I've confirmed this as a bug, will release a fix today. Thanks for spotting it! (BTW schema and url have equivalent effects in configurating schema associated with a file, I'll also change its default value to suggest that)
