### ISSUE TITLE
Trigger Suggestions when Typing ""

### ISSUE THREAD

**Issue by Bryan-Legend** [BlueGlassBlock/better-json5#9]
When I was using the built in JSON mode to edit my files with a schema, I could press " to begin typing a key and it would list all of the available key via intellisense.

That's doesn't seem to be possible with this extension. The intellisense pops up when I type the first character of a key but I can't get a full list to browse thru.

Please list the full list of keys when I have an empty key via typing "". Or is there a hot key for this? I tried CTRL+. but it said no code actions available.

**Comment by Bryan-Legend** [comment]
![image](https://github.com/user-attachments/assets/dab47aa8-5dc2-40af-b052-7b6aadda8acd)

**Comment by BlueGlassBlock** [comment]
Ctrl + Space triggers code completion correctly on my side:
![image](https://github.com/user-attachments/assets/ad941426-d33f-43b5-998f-f1ac536d97d1)
